### ISSUE TITLE
Want to ask 

### ISSUE THREAD

**Issue by BhJaipal** [Debargha-Mitra-Roy/Debargha-Mitra-Roy#1]
Is this possible to make vscode app not vscode.dev available for Android?
    - [BhJaipal](https://github.com/BhJaipal)

**Comment by Debargha-Mitra-Roy** [comment]
Sorry for late comments.

**Comment by Debargha-Mitra-Roy** [comment]
Sorry for late comments.

Here is the link of your answer : <a href="https://stackoverflow.com/questions/36290113/can-vs-code-run-on-android">LINK</a>

**Comment by Debargha-Mitra-Roy** [comment]
Make sure next time you ask me through social media @BhJaipal
